spring:
  application:
    name: rpc-rabbitmq-server
logging:
  level:
    com.dchavez: DEBUG
    org.springframework.web: WARN
#    io.jaegertracing: INFO
#    io.opentracing: INFO
server:
  port: 8087
opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
